### ISSUE TITLE
Nabin: Summarize what you've learned in brief presentation.

### ISSUE THREAD

**Issue by calebheinzman** [Deep-Stonks-Group/Forecasting-Team-3#3]

**Comment by nabingiri** [comment]
- Worked on a simple stock predicting program using LSTM. 
[https://github.com/NabinGiri/Predict_Stock/blob/fc9b7db45586327a357f434315b43a4e3c49bf3a/LSTM_Stocks.ipynb](url)

- Working on presentation,
